# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [2]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [8]:
#todo: 
# lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# array = np.array(lista)
# print(array)

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo:
array = np.zeros((5),int)
print(array)

array[2] = 5
print(array)

[0 0 0 0 0]
[0 0 5 0 0]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [13]:
#todo: 
matriz = np.random.rand(3,3)
print(matriz)

[[0.73706532 0.99417661 0.49521493]
 [0.89746901 0.95437066 0.45838524]
 [0.36222006 0.09175482 0.64391088]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [19]:
#todo:
# arr = np.array([10, 20, 30, 40, 50])
# arr1 = np.array([5, 5, 5, 5, 5])

# suma = np.add(arr, arr1)
# print("El resultado de la suma es: ",suma)

# numero_aleaotrio = randint(0, 100)
# print("El numero aleatorio es: ",numero_aleaotrio)

# multiplicacion = np.multiply(suma, numero_aleaotrio)
# print("El resultado de la multiplicacion es: ",multiplicacion)

arr = np.array([10, 20, 30, 40, 50])

arr_suma = arr + 5
print("Array luego de sumar 5:", arr_suma)

numero_aleatorio = randint(1, 100)
print("Número aleatorio:", numero_aleatorio)

multiplicado = arr_suma * numero_aleatorio
print("Resultado final:",  multiplicado)

Array luego de sumar 5: [15 25 35 45 55]
Número aleatorio: 75
Resultado final: [1125 1875 2625 3375 4125]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [22]:
#todo:
print(np.eye(4))

# print(np.eye(4,k=0))

# print(np.eye(4,4,k=0))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [43]:
#todo: 
array = np.arange(0,21,2)
otro_array = np.random.rand(array.size)
print(array)
print(otro_array)

suma = np.add(array, otro_array)
resta = np.subtract(array, otro_array)
multiplicacion = np.multiply(array, otro_array)
division = np.divide(array, otro_array)

print(suma)
print(resta)
print(multiplicacion)
print(division)


[ 0  2  4  6  8 10 12 14 16 18 20]
[0.33722167 0.34016132 0.80296324 0.45277793 0.634037   0.54176569
 0.2822018  0.25694633 0.01409044 0.00722172 0.32358702]
[ 0.33722167  2.34016132  4.80296324  6.45277793  8.634037   10.54176569
 12.2822018  14.25694633 16.01409044 18.00722172 20.32358702]
[-0.33722167  1.65983868  3.19703676  5.54722207  7.365963    9.45823431
 11.7177982  13.74305367 15.98590956 17.99277828 19.67641298]
[0.         0.68032264 3.21185294 2.7166676  5.07229597 5.41765693
 3.38642161 3.59724868 0.22544706 0.12999097 6.47174047]
[   0.            5.87956326    4.98154812   13.25152917   12.61756024
   18.45816399   42.5227619    54.48608575 1135.5215683  2492.48080254
   61.80717561]
